import { Gear } from './types';

export const AVAILABLE_GEAR: Gear[] = [
  {
    id: 1,
    name: 'BANTAL',
    pricePerDay: 5000,
    imageUrl: 'https://picsum.photos/seed/ba/400/300',
    category: 'Other',
  },
  {
    id: 2,
    name: 'CARRIER AVTECK 60L',
    pricePerDay: 20000,
    imageUrl: 'https://picsum.photos/seed/cr-04/400/300',
    category: 'Packs',
  },
  {
    id: 3,
    name: 'CARRIER CONSINA',
    pricePerDay: 20000,
    imageUrl: 'https://picsum.photos/seed/cr-02/400/300',
    category: 'Packs',
  },
  {
    id: 4,
    name: 'CARRIER GGLACIER 52L',
    pricePerDay: 20000,
    imageUrl: 'https://picsum.photos/seed/cr-gglacier-52l/400/300',
    category: 'Packs',
  },
  {
    id: 5,
    name: 'CARRIER OSPREY',
    pricePerDay: 35000,
    imageUrl: 'https://picsum.photos/seed/cr-osprey/400/300',
    category: 'Packs',
  },
  {
    id: 6,
    name: 'CARRIER REI 60L',
    pricePerDay: 25000,
    imageUrl: 'https://picsum.photos/seed/cr-rei-60l/400/300',
    category: 'Packs',
  },
  {
    id: 7,
    name: 'CARRIER SUNATURE 60L',
    pricePerDay: 20000,
    imageUrl: 'https://picsum.photos/seed/cr-sunature-60l/400/300',
    category: 'Packs',
  },
  {
    id: 8,
    name: 'FLYSHEET 3X3',
    pricePerDay: 8000,
    imageUrl: 'https://picsum.photos/seed/flysheet-3x3/400/300',
    category: 'Shelter',
  },
  {
    id: 9,
    name: 'FLYSHEET 3X4',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/flysheet-3x4/400/300',
    category: 'Shelter',
  },

  {
    id: 10,
    name: 'FLYSHEET 4X6',
    pricePerDay: 20000,
    imageUrl: 'https://picsum.photos/seed/flysheet-4x6/400/300',
    category: 'Shelter',
  },
  {
    id: 11,
    name: 'GAS PORTABLE',
    pricePerDay: 15000,
    imageUrl: 'https://picsum.photos/seed/gas-portable/400/300',
    category: 'Cooking',
  },
  {
    id: 12,
    name: 'HAMMOCK',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/hammock/400/300',
    category: 'Sleeping',
  },
  {
    id: 13,
    name: 'HEADLAMP',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/headlamp/400/300',
    category: 'Lighting',
  },
  {
    id: 14,
    name: 'HEADLAMP / BATERAI',
    pricePerDay: 15000,
    imageUrl: 'https://picsum.photos/seed/headlamp-batt/400/300',
    category: 'Lighting',
  },
  {
    id: 15,
    name: 'HYDROPACK CREDIFOX',
    pricePerDay: 15000,
    imageUrl: 'https://picsum.photos/seed/hydro-credifox/400/300',
    category: 'Other',
  },
  {
    id: 16,
    name: 'HYDROPACK MONTE',
    pricePerDay: 15000,
    imageUrl: 'https://picsum.photos/seed/hydro-monte/400/300',
    category: 'Other',
  },
  {
    id: 17,
    name: 'ISI ULANG GAS',
    pricePerDay: 7000,
    imageUrl: 'https://picsum.photos/seed/isi-ulang-gas/400/300',
    category: 'Cooking',
  },
  {
    id: 18,
    name: 'KOMPOR 01',
    pricePerDay: 5000,
    imageUrl: 'https://picsum.photos/seed/kompor-01/400/300',
    category: 'Cooking',
  },
  {
    id: 19,
    name: 'KOMPOR 02',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/kompor-02/400/300',
    category: 'Cooking',
  },
  
  {
    id: 20,
    name: 'KURSI SPEED',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/kursi-speed/400/300',
    category: 'Other',
  },
  {
    id: 21,
    name: 'KURSI WD',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/kursi-wd/400/300',
    category: 'Other',
  },
  {
    id: 22,
    name: 'LAMPU TENDA',
    pricePerDay: 5000,
    imageUrl: 'https://picsum.photos/seed/lampu-tenda/400/300',
    category: 'Lighting',
  },
  {
    id: 23,
    name: 'LAMPU TENDA / BATERAI',
    pricePerDay: 15000,
    imageUrl: 'https://picsum.photos/seed/lampu-tenda-baterai/400/300',
    category: 'Lighting',
  },
  {
    id: 24,
    name: 'MATRAS',
    pricePerDay: 5000,
    imageUrl: 'https://picsum.photos/seed/matras/400/300',
    category: 'Sleeping',
  },
  {
    id: 25,
    name: 'MEJA BIG ADVENTURE',
    pricePerDay: 20000,
    imageUrl: 'https://picsum.photos/seed/meja-big-adventure/400/300',
    category: 'Other',
  },
  {
    id: 26,
    name: 'NESTING',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/nesting/400/300',
    category: 'Cooking',
  },
  {
    id: 27,
    name: 'SEWA GAS',
    pricePerDay: 7000,
    imageUrl: 'https://picsum.photos/seed/sewa-gas/400/300',
    category: 'Cooking',
  },
  {
    id: 28,
    name: 'SLEEPING BAG',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/sleeping-bag/400/300',
    category: 'Sleeping',
  },
  {
    id: 29,
    name: 'TENDA 10P HL-8916',
    pricePerDay: 120000,
    imageUrl: 'https://picsum.photos/seed/tenda-10p-hl-8916/400/300',
    category: 'Shelter',
  },
  {
    id: 30,
    name: 'TENDA 2P DISERT-FOX UL',
    pricePerDay: 35000,
    imageUrl: 'https://picsum.photos/seed/tenda-2p-disert-fox/400/300',
    category: 'Shelter',
  },
  {
    id: 31,
    name: 'TENDA 2P NAVAGEO UL',
    pricePerDay: 35000,
    imageUrl: 'https://picsum.photos/seed/tenda-2p-navageo/400/300',
    category: 'Shelter',
  },
  {
    id: 32,
    name: 'TENDA 4P DHAULAGIRI TERRA',
    pricePerDay: 45000,
    imageUrl: 'https://picsum.photos/seed/tenda-4p-dhaulagiri/400/300',
    category: 'Shelter',
  },
  {
    id: 33,
    name: 'TENDA 4P JAVA PRO',
    pricePerDay: 50000,
    imageUrl: 'https://picsum.photos/seed/tenda-4p-java-pro/400/300',
    category: 'Shelter',
  },
  {
    id: 34,
    name: 'TENDA 4P LWY UL',
    pricePerDay: 50000,
    imageUrl: 'https://picsum.photos/seed/tenda-4p-lwy/400/300',
    category: 'Shelter',
  },
  {
    id: 35,
    name: 'TENDA 4P PAVILIO',
    pricePerDay: 40000,
    imageUrl: 'https://picsum.photos/seed/tenda-4p-pavilio/400/300',
    category: 'Shelter',
  },
  {
    id: 36,
    name: 'TENDA 4P TENDAKI',
    pricePerDay: 45000,
    imageUrl: 'https://picsum.photos/seed/tenda-4p-tendaki/400/300',
    category: 'Shelter',
  },
  {
    id: 37,
    name: 'TENDA 6P MANDALA',
    pricePerDay: 75000,
    imageUrl: 'https://picsum.photos/seed/tenda-6p-mandala/400/300',
    category: 'Shelter',
  },
  {
    id: 38,
    name: 'TENDA 6P NAVAGEO UL',
    pricePerDay: 75000,
    imageUrl: 'https://picsum.photos/seed/tenda-6p-navageo/400/300',
    category: 'Shelter',
  },
  {
    id: 39,
    name: 'TIANG FLYSHEET',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/tiang-flysheet/400/300',
    category: 'Shelter',
  },
  {
    id: 40,
    name: 'TREKKING POLE',
    pricePerDay: 10000,
    imageUrl: 'https://picsum.photos/seed/trekking-pole/400/300',
    category: 'Other',
  }
];
